name: Test Ingress

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create Kind Cluster with config
        run: |
          bash ./create-kind
      - name: Get Kube's Info
        run: |
          kubectl cluster-info
      - name: Install ingress-nginx
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - name: Wait for Resource (hack)
        run: |
          sleep 20
      - name: Wait for ingress-nginx's Set-up
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s
      - name: Deploy Some Apps
        run: |
          kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml
      - name: CURL Ingress
        run: |
          curl localhost/foo/hostname
          curl localhost/bar/hostname
