name: Create Cluster

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.18.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create cluster with Kind Config
        run: bash ./kind-config
      - name: Install ingress-nginx
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - name: Testing
        run: |
            kubectl cluster-info
            kubectl get pods -A
